### ISSUE TITLE
Cannot install as instructed in quickstart guide

### ISSUE THREAD

**Issue by carlthome** [spotify/klio#113] opened 2020-11-05 20:53 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
type: bug

## Environment

- `klio` version(s): N/A
- Operating System(s): Ubuntu 20.04.1 LTS x86_64
- Python version(s): 3.8.5

## What happened
Running `pipx install klio-cli` on a new Python install on Ubuntu 20.04 after running `sudo apt install pipx python3-venv` leads to an error about package incompatibilities.

```sh
carl@workstation:~/klio_quickstart$ pipx install klio-cli

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

google-api-python-client 1.12.5 requires google-api-core<2dev,>=1.21.0, but you'll have google-api-core 1.20.1 which is incompatible.
klio-core 0.2.0 requires google-api-python-client<1.12,>=1.10.0, but you'll have google-api-python-client 1.12.5 which is incompatible.
Could not find package klio-cli. Is the name correct?
```

## What you expected to happen
I expected to be able to run `klio --version` just after.

## How to reproduce it (as minimally and precisely as possible)
`pipx install klio-clio`, I assume. Perhaps it's specific to my Ubuntu install's Python somehow? All I've really done AFAIK is to run `sudo apt install pipx python3-venv` on a clean slate.

**Comment by carlthome** [comment] 2020-11-05 21:01
Confused, I've also tried:
```
docker run --rm -it python:3.8 bash
pip install pipx
pipx install klio-cli
```
which had the precise same error:
```sh
root@536721bc1c58:/# pipx install klio-cli
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

google-api-python-client 1.12.5 requires google-api-core<2dev,>=1.21.0, but you'll have google-api-core 1.20.1 which is incompatible.
klio-core 0.2.0 requires google-api-python-client<1.12,>=1.10.0, but you'll have google-api-python-client 1.12.5 which is incompatible.
Internal error with venv metadata inspection.

Unable to install klio-cli.
Check the name or spec for errors, and verify that it can be installed with pip.

```

**Comment by econchick** [comment] 2020-11-05 21:14
Hey @carlthome - thanks for the issue & sorry for the trouble. We definitely see issues with dependency conflicts, and it _might_ be resolved with `pipx install klio-cli --pip-args="--use-feature=2020-resolver"`. If you're able to try that out, lmk. Otherwise I'll try to reproduce it myself and hopefully figure out a fix.

**Comment by econchick** [comment] 2020-11-05 21:28
@carlthome I just did this successfully:

```sh
docker run --rm -it python:3.8 bash

pip install pipx
# update PATH to include pipx's install path
echo "PATH=$PATH:/root/.local/bin" >> ~/.bashrc && source ~/.bashrc

# confirm issue - this indeed errors out
pipx install klio-cli # errors out

# retry with the added arg - successfully installs
pipx install klio-cli --pip-args="--use-feature=2020-resolver"
klio --version
klio-cli, version 1.0.1
```

LMK how this works for you. If it works, I'll then update our docs accordingly.

**Comment by carlthome** [comment] 2020-11-05 22:26
That worked great! Thanks!

```sh
root@7ec58f8443ee:/# klio
Usage: klio [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  image    Manage a job's Docker image.
  job      Create and manage Klio jobs.
  message  Manage a job's message queue via Pub/Sub.
```

**Comment by carlthome** [comment] 2020-11-05 22:26
Perhaps this issue should remain open until the docs are updated with a hint, as you mentioned. :koala:

**Comment by econchick** [comment] 2020-11-06 15:17
Closing this now since [installation docs](https://docs.klio.io/en/latest/quickstart/installation.html) have been updated :)

**Closed by econchick** 2020-11-06 15:17 UTC
